name: finance_app
description: An finance app created with Flutter and Firebase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.0
  fl_chart: ^0.55.2
  firebase_core: ^2.4.1
  sqflite: ^2.2.2
  path: ^1.8.2
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2
  either_dart: ^0.3.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Philippa
      fonts:
        - asset: assets/fonts/Philippa-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Philippa-Light.ttf
          weight: 300
        - asset: assets/fonts/Philippa-Book.ttf
        - asset: assets/fonts/Philippa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Philippa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Philippa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Philippa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Philippa-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Philippa-Black.ttf
          weight: 900
